### ISSUE TITLE
status command failing

### ISSUE THREAD

**Issue by ifeghali** [deitch/imapper#1]
Imap command:

`TAG5 STATUS "INBOX" (MESSAGES UNSEEN UIDNEXT)\r\n'`

Is triggering the following error:

```
/home/ec2-user/node_modules/ses-imap/node_modules/imapper/lib/commands/status.js:37
        mailbox = connection.server.getMailbox(path),
                                    ^
TypeError: Object #<IMAPServer> has no method 'getMailbox'
```

I have checked hoodiecrow code and getMailbox was indeed a method in the server. It looks like it was ported to the storage plugin [imapper-storage-s3ses](https://github.com/seelang2/imapper-storage-s3ses).

**Comment by deitch** [comment]
> It looks like it was ported to the storage plugin

Good catch. Checking now...

**Comment by deitch** [comment]
Yeah, that whole part was abstracted to the connection. Must have missed `status` and `unsubscribe` on the earlier runs.
