### ISSUE TITLE
Change the way of communication ?

### ISSUE THREAD

**Issue by bibudha** [deitch/imapper#3]
Hello
I have a mail server where I used database for storing mails. So can I change the way of communication of your plugin as an IMAP server. Means can i use your plugin and send data to mail client as I want from my database ?

**Comment by deitch** [comment]
Hi @bibudha .

It already does. You use a storage driver to implement any backend. I have had it storing emails in files, memory and AWS DynamoDB. 

See https://github.com/deitch/imapper#imapper-storage-memory for the available memory storage plugin and https://github.com/deitch/imapper/blob/master/plugins/STORAGE-PLUGIN.md for instructions and the API.

**Comment by bibudha** [comment]
Ok....let me try with these....but one thing do all imap clients receive
the same way or i have to write code for all imap clients separately

**Comment by deitch** [comment]
> do all imap clients receive the same way or i have to write code for all imap clients separately

Not sure I understand the question. imap clients talk the IMAP protocol to the server. The server independently manages storage in the backend.

**Comment by bibudha** [comment]
Yes that is what I want. If I install your plugin do all IMAP clients can talk to me through this or I need to change something else ?

**Comment by deitch** [comment]
Client <-> Server <-> Storage

* Client: whatever IMAP client you have (library, CLI, Thunderbird, whatever)
* Server: this lib
* Storage: whatever storage you use, with the driver one of the provided ones or your own plugin

**Comment by bibudha** [comment]
Thank You.....
